[package]
name = "agl-terminal-client"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
agl-exec.workspace = true
agl-terminal.workspace = true
agl-terminal-protocol.workspace = true
futures-util.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true

[dev-dependencies]
serde_json.workspace = true
