[package]
name = "agl-inference-worker"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
agl-actions.workspace = true
agl-config.workspace = true
agl-content.workspace = true
agl-inference.workspace = true
agl-ids.workspace = true
agl-llama-cpp-sys.workspace = true
agl-oven.workspace = true
anyhow.workspace = true
libc.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true

[build-dependencies]
agl-llama-cpp-sys.workspace = true
libc.workspace = true
sha2.workspace = true

[dev-dependencies]
agl-config.workspace = true
agl-content.workspace = true
agl-ids.workspace = true
agl-oven.workspace = true

[[test]]
name = "sandbox_linux"
path = "tests/sandbox_linux.rs"
harness = false
