[package]
name = "agl-assets"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
build = "build.rs"

[dependencies]
agl-artifact.workspace = true

[build-dependencies]
agl-artifact.workspace = true
agl-config.workspace = true
sha2.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
toml.workspace = true

[dev-dependencies]
agl-config.workspace = true
sha2.workspace = true
