[package]
name = "agl-app"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
agl-artifact.workspace = true
agl-assets.workspace = true
agl-extension.workspace = true
agl-exec.workspace = true
agl-chat.workspace = true
agl-function.workspace = true
agl-kernel.workspace = true
agl-model.workspace = true
agl-runtime.workspace = true
agl-skill.workspace = true
anyhow.workspace = true
agl-content.workspace = true
agl-ids.workspace = true
agl-process.workspace = true
agl-terminal.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
