[package]
name = "agl-app"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
agl-capabilities.workspace = true
agl-content.workspace = true
agl-ids.workspace = true
agl-process.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
